version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Building the React app...
      - npm run build
      - echo Syncing build directory with S3...
      - aws s3 sync build/ s3://aws-angular-bucket-0209/ --delete

artifacts:
  files:
    - '**/*'
  base-directory: build
